name: publishtools
on:
  push:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name : Install V dependencies
        run: sudo apt install -y libgc-dev
      - name: Install V lang
        run:  rm -rf v 2>&1 && rm -rf ~/.vmodules  2>&1 && git clone https://github.com/vlang/v && cd v && make && sudo ./v symlink && cd ..
      - name: Install pubtools dependecncies
        run:  v install patrickpissurno.redis && v install despiegk.crystallib && v install nedpals.vex
      - name: Build pubtools
        run: rm -rf publishtools 2>&1 && git clone https://github.com/crystaluniverse/publishtools && cd publishtools/crystaltools && v -cc gcc -gc boehm -cflags -static -d net_blocking_sockets -d static_boehm publishtools.v && sudo mv publishtools /usr/local/bin && sudo chmod u+x /usr/local/bin/publishtools
      - name: change dir to home
        run: cd
      - name: Run publishtools
        run: publishtools
      - name: Build pubtools with sanitizers
        run: |
          rm -rf publishtools 2>&1
          git clone https://github.com/crystaluniverse/publishtools
          cd publishtools/crystaltools
          v -cc gcc -gc boehm -cflags "-fsanitize=undefined" -d net_blocking_sockets -d static_boehm publishtools.v
          sudo mv publishtools /usr/local/bin
          sudo chmod u+x /usr/local/bin/publishtools
      - name: create sites.json at home
        uses: finnp/create-file-action@1.0.0
        env:
            FILE_NAME: sites.json
            FILE_DATA: '[{\n                "name": "info_publishtools",\n                "git_url":  "https://github.com/crystaluniverse/info_publishtools",\n                "branch":       "",\n                "pull": false,\n                "reset":        false,\n                "cat":  0,\n                "shortname":    "publishtools",\n                "path_code":    "",\n                "domains":      ["publishtools-info.threefold.io"],\n                "descr":        "Publishtools Info",\n                "groups":       [],\n                "acl":  [],\n                "trackingid":   "",\n                "opengraph":    {\n                        "title":        "",\n                        "description":  "",\n                        "url":  "",\n                        "type_":        "article",\n                        "image":        "",\n                        "image_width":  "1200",\n                        "image_height": "630"\n                }\n        }]'

      - name: Run publishtools flatten
        run: publishtools flatten
      - name: cleaning
        run: |
          rm -rf ~/codewww
          rm -rf ~/.publisher
      - name: Print Status
        run: echo "üçè This job's status is ${{ job.status }}."
